language: python

install: pip install mkdocs

script: sed 's/docs\///g' README.md > docs/index.md && mkdocs build && bash docs/publish-docs.sh

notifications:
  email: false

branches:
  only:
  - master